language: java

before_script:
  - sed '/tasks\.withType<Test>/,$d' build.gradle.kts > t && mv -f t build.gradle.kts

script:
  - ./gradlew build

after_script:
  - git reset --hard HEAD

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

matrix:
  include:
    - name: Ubuntu 18.04 OpenJDK 11
      dist: bionic
      jdk:
        - openjdk11
      script:
        - ./gradlew build
        - gradle clean build

    - name: Ubuntu 16.04 OpenJDK 8
      dist: xenial
      jdk:
        - openjdk8
      script:
        - ./gradlew build
        - gradle clean build

    - name: Ubuntu 16.04 OpenJDK 11
      dist: xenial
      jdk:
        - openjdk11
      script:
        - ./gradlew build
        - gradle clean build

    - name: macOS 10.13 JDK 8
      os: osx
      osx_image: xcode9.3

    - name: macOS 10.13 OpenJDK 11
      os: osx
      osx_image: xcode10.1

    - name: macOS 10.14 OpenJDK 12
      os: osx
      osx_image: xcode11
